### ISSUE TITLE
Error:sudo make install-file not found

### ISSUE THREAD

**Issue by johnsageeek** [fastoe/RTL8811CU#4]
I follow the steps to "make" and run the "make install" but receive "Error"  
"root@lmde-6:/home/milesjp/RTL8811CU# sudo make install
mkdir -p /lib/modules/6.1.0-13-amd64/kernel/drivers/net/wireless/realtek/rtl8821cu/
install -p -m 644 8821cu.ko  /lib/modules/6.1.0-13-amd64/kernel/drivers/net/wireless/realtek/rtl8821cu/
install: cannot stat '8821cu.ko': No such file or directory
make: *** [Makefile:2224: install] Error 1"

System_Info:
OS: LMDE 6 (faye) x86_64 
Host: Inspiron 7520 A14 
Kernel: 6.1.0-13-amd64 
Packages: 2082 (dpkg) 
Shell: bash 5.2.15 
Resolution: 1920x1080 
DE: Cinnamon 5.8.4 
WM: Mutter (Muffin) 
WM Theme: Mint-Y-Dark-Aqua (Mint-Y) 
Theme: Mint-Y-Aqua [GTK2/3] 
Icons: Mint-Y-Sand [GTK2/3] 
Terminal: gnome-terminal 
CPU: Intel i5-3210M (4) @ 3.100GHz 
GPU: AMD ATI Radeon HD 7730M 
GPU: Intel 3rd Gen Core processor Graphics Controller 
Memory: 3469MiB / 5793MiB

**Comment by tc0nn** [comment]
Did the "make" succeed?
